---
- name: Setting up local groups
  group:
    name: admin
    state: present

- name: Create local users
  user:
    name: "{{ item.username }}"
    comment: Created by Ansible
    group: admin
  with_items: "{{ users }}"

- name: Distribute ssh-key
  authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', '/{{ item.key }}') }}"
      state: present
  with_items: "{{ users }}"

- name: Ensuring sudo permissions
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin ALL='
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s' 

- name: Configuring sshd
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Allowusers {% for item in users %} {{ item.username }} {% endfor %} 
      PermitRootLogin no
      PasswordAuthentication no
  notify: Restarting sshd service

- name: Installing fail2ban
  yum:
    name: fail2ban
    state: present

- name: Configuring fail2ban
  template:
    src: jail.local.j2
    dest: "{{ jail_local }}"

- name: Further configuring fail2ban
  template:
    src: ssh-jail.local.j2
    dest: "{{ ssh_jail_local }}" 

- name: Starting and enabling fail2ban
  systemd:
    state: started
    enabled: yes
    name: fail2ban
